# Generated by Django 6.0 on 2025-12-14 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('raw_answers', models.JSONField()),
                ('ai_raw_response', models.TextField(blank=True, default='')),
                ('dashboard_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('review_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis', to='review.reviewsession')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='ai_analysis_status_986e05_idx'), models.Index(fields=['-created_at'], name='ai_analysis_created_d8167d_idx')],
            },
        ),
    ]
